##############################################################################
# Dockerfile de construção do container WebApp utilizado pelo SEI e pelo SIP #
##############################################################################

FROM schickling/mailcatcher

MAINTAINER PEN - Processo Eletrônico Nacional

EXPOSE 1080

