################################################################################
# Dockerfile de construção do container do FakeSMTP
#
# Container preparado e configurado para uso em desenvolvimento e testes
################################################################################

MAINTAINER PEN - Processo Eletrônico Nacional
FROM schickling/mailcatcher

EXPOSE 1080
