##############################################################################
# Dockerfile de construção do container WebApp utilizado pelo SEI e pelo SIP #
##############################################################################

# Definição da imagem de base para o CentOS 6.X
FROM memcached

# Autor e mantenedor do container
MAINTAINER PEN - Processo Eletrônico Nacional

# Exposição da porta de conexão ao Apache
EXPOSE 11211


