SHUTDOWN;
STARTUP MOUNT;
ALTER SYSTEM ENABLE RESTRICTED SESSION;
ALTER SYSTEM SET JOB_QUEUE_PROCESSES=0;
ALTER DATABASE OPEN;
ALTER DATABASE CHARACTER SET INTERNAL_USE WE8MSWIN1252;
ALTER DATABASE NATIONAL CHARACTER SET INTERNAL_USE AL16UTF16;
SHUTDOWN IMMEDIATE;
STARTUP;

CREATE TABLESPACE SEI DATAFILE '/u01/app/oracle/oradata/XE/sei.dbf' SIZE 20M AUTOEXTEND ON;
CREATE TABLESPACE SIP DATAFILE '/u01/app/oracle/oradata/XE/sip.dbf' SIZE 20M AUTOEXTEND ON;

CREATE USER sei_user IDENTIFIED BY sei_user;
CREATE USER sip_ser IDENTIFIED BY sip_user;

GRANT ALL PRIVILEGES TO sei_user;
GRANT ALL PRIVILEGES TO sip_user;

EXIT;
