#!/bin/bash  
#ss description: Tomcat Start Stop Restart  
# processname: tomcat  
# chkconfig: 234 20 80  
#JAVA_HOME=/usr/java/jdk1.7.0_05  
#export JAVA_HOME  
#PATH=$JAVA_HOME/bin:$PATH  
#export PATH  
CATALINA_HOME=/opt/jodconverter-tomcat-2.2.2
  
case $1 in  
start)  
	sh $CATALINA_HOME/bin/startup.sh  
;;   
stop)     
	sh $CATALINA_HOME/bin/shutdown.sh  
;;   
restart)  
	sh $CATALINA_HOME/bin/shutdown.sh  
	sh $CATALINA_HOME/bin/startup.sh  
;;   
esac      
exit 0  
