################################################################################
# Dockerfile de construção do container MailCatcher utilizado pelo SEI e SIP
#
# Container preparado e configurado para uso em desenvolvimento e testes
################################################################################

FROM schickling/mailcatcher
MAINTAINER Guilherme Andrade Del Cantoni <guilherme.cantoni@economia.gov.br>

############################# INÍCIO DA INSTALAÇÃO #############################
ENV TERM xterm

#COPY install.sh /install.sh
#COPY entrypoint.sh /entrypoint.sh

#RUN sh /install.sh
############################## FIM DA INSTALAÇÃO ###############################

EXPOSE 1080
#CMD ["/entrypoint.sh"]
